---
title: "Fatality Analysis Reporting"
author: "Subrata Baguli"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fatality Analysis Reporting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(fars)
```

## Data source

The data files were downloaded directly from the [ website](https://d3c33hcgiwev3.cloudfront.net/_e1adac2a5f05192dc8780f3944feec13_fars_data.zip?Expires=1604534400&Signature=RTTvUAKz8DKWFiSEcAetz-uqBOzv79moF3uW0TbPA8k8fvG6Pa~o1wndjQsxlNKDxFWVONipYXks9nQ~G3zuKUfDj0ufW2d0ITHZlmi9VqjXjoTbW4MjXzoLX8I-CLjs-OG4VzhK6dewCktT1k2mIVfRodd72Kzu3BQTcqK5lZI_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A).

Three data files to test this package are:

* accident_2013.csv.bz2

* accident_2014.csv.bz2

* accident_2015.csv.bz2



## Dependencies

You need to load the following packages before starting:

```{r, echo=TRUE, include=TRUE}
library(dplyr)
library(maps)
library(readr)
library(tidyr)
```
